apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"springboot-app"},"name":"springboot-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"springboot-app"}},"template":{"metadata":{"labels":{"app":"springboot-app"}},"spec":{"containers":[{"image":"kaushal2118/noneimage","name":"springboot-container","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2025-05-26T07:10:06Z"
  generation: 1
  labels:
    app: springboot-app
  name: springboot-deployment
  namespace: default
  resourceVersion: "5466"
  uid: 87c9fb9d-07ff-42ee-9f5e-1f89e0b9f821
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: springboot-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springboot-app
    spec:
      containers:
      - image: kaushal2118/noneimage
        imagePullPolicy: Always
        name: springboot-container
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-26T07:10:07Z"
    lastUpdateTime: "2025-05-26T07:10:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-26T07:10:06Z"
    lastUpdateTime: "2025-05-26T07:10:07Z"
    message: ReplicaSet "springboot-deployment-7c8fd757d7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
