apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8080        # Service port
      targetPort: 8080  # Container port
      nodePort: 32682   # Optional fixed NodePort (must be in range 30000-32767)

