apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-26T07:13:52Z"
  labels:
    app: springboot-app
  name: spring-svc
  namespace: default
  resourceVersion: "5777"
  uid: 3373ac81-17c0-4cca-ad24-acee3fc4f534
spec:
  clusterIP: 10.100.136.181
  clusterIPs:
  - 10.100.136.181
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30150
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
